functions.py

Made some changes to find primes for so it actually works. Also gave prime_check a more intuitive name

Made find_primes work

---

functions.py

Added prime_factors to find the prime-factors of a number
Added zeros to create a list of zeros of any 2-dimensional dimensions

Added new functions

---

functions.py

Also fixed an error in prime_factors

Added totient function

---

functions.py

Caching factorial results. Append never raises Index error.
#5

Improve `louville_distance` function

---

series_sum.py

Added few summation functions which I found is very useful in many cases

Added few sum functions

---

Python/armstrong.py
Python/find_primes_old.py
Python/louville_distance.py
Python/product.py
Python/taylor_sine.py
Python/totient.py

Related to Code Style Issue #22

Fixes to fit PEP8 requirements

---

Python/unique_elements.py

Get unique elements and frequency from a given list of numbers.

Added function to get unique elements

---

Python/parabola.py

#4 _Hacktoberfest!_
Wrote three simple functions that let you find the **delta**, **focus** and **vertex** of a quadratic equation.

Added functions for the parabola.

---

Python/area_of_traingle.py
Python/traingle.py

Function for calculating the area of traingle from the length of sides.

Added a python file (area_of_traingle.py) containing the heron's formula.

---

Python/simple_interest.py

Function to calculate simple interest.

Added a math function for simple interest

---

Python/cylinder.py

Finds the area/volume of a cylinder given the radius and height.

Added cylinder.py

---

Python/rpd.py

Calculates the relative percent difference of two numbers

Added rpd.py

---

Python/amicable_and_incompletely_amicable.py
Python/bretschneider.py
Python/find_primes.py
Python/series_sum.py
Python/triangle.py

I'm kind of new to this. Hope I did it right and that it was somewhat helpful.
#Hacktoberfest

Fixed typos and renamed a file which had a typo for the name

---

Python/lcm.py

issue #4 
This code is to check the least common multiple of two numbers(a,b).

least common multiple's of two numbers

---

Python/estimate_pi.py

Estimate Pi

---

Python/perfect_square.py

Imported math.sqrt as _sqrt to show it is private and shouldn't be used when this module is imported and removed unnecessary else statement.

Cleaned up the code in perfect_square.py

---

Python/pascal_triangle.py

Added a function to return a Pascal Triangle as a 2D list.

Add Pascal Triangle function

---

Python/count_digits.py

added new function count_digits.py

add function count_digits

---

Python/polynomial_evaluation.py

Polynomial Evaluation method in python
evaluate_poly(poly, x)
poly :  is a tuple which consists of coefficients of the polynomial equation
x : value of x in f(x)
Example: 
```
poly = (0.0, 0.0, 5.0, 9.3, 7.0) 
x = -13
print (evaluate_poly(poly, x))
>>> 180339.9
```

Polynomial Evaluation Function

---

Python/quadratic_formula.py

Quadratic formula solver with no external dependencies; takes an input of a, b and c (from the standard form) and returns a tuple with both possible solutions for x.

Added basic quadratic formula solver

---

Python/Cosine_distance.py

Program to compute Cosine Distance between an two given vectors

created cosine_distance.py

---

Python/n-nacci.py

Makes it possible to use your own parameters and mess around with Fibonacci.
Added a cli option too.

Customized Fibonacci
